export enum ActionTypes {
    PRODUCT_SET ='[PRODUCT] PRODUCT_SET',
    PRODUCT_CLEAR ='[PRODUCT] PRODUCT_CLEAR',

    PRODUCTLIST_SET ='[PRODUCTLIST] PRODUCTLIST_SET',
    PRODUCTLIST_CLEAR ='[PRODUCTLIST] PRODUCTLIST_CLEAR',

    SHOPPINGCART_ADD ='[SHOPPINGCART] SHOPPINGCART_ADD',
    SHOPPINGCART_REMOVE ='[SHOPPINGCART] SHOPPINGCART_REMOVE',
    SHOPPINGCART_INCREMENT ='[SHOPPINGCART] SHOPPINGCART_INCREMENT',
    SHOPPINGCART_DECREMENT ='[SHOPPINGCART] SHOPPINGCART_DECREMENT',
    SHOPPINGCART_CLEAR ='[SHOPPINGCART] SHOPPINGCART_CLEAR',
    SHOPPINGCART_TOTAL ='[SHOPPINGCART] SHOPPINGCART_TOTAL',
    SHOPPINGCART_AMOUNT ='[SHOPPINGCART] SHOPPINGCART_AMOUNT'
}